### ISSUE TITLE
When Ratelimited exception occurs in middleware, django logging doesn't get the request data

### ISSUE THREAD

**Issue by rschwiebert** [jsocol/django-ratelimit#143] opened 2018-05-30 02:43 UTC
I've been using the AdminEmailHandler to forward errors from my website, but the problem is that the ratelimited exceptions that come through are missing something that is useful, namely the info about the identity of the sender.

It looks like the handler attaches the request if it exists, but apparently in the case of the ratelimit middleware it's falling into this except clause:

    ` except Exception:
            subject = '%s: %s' % (
                record.levelname,
                record.getMessage()
            )
            request = None`

   in the implementation of AdminEmailHandler https://docs.djangoproject.com/en/1.11/_modules/django/utils/log/

The resulting email contains the url of the ratelimited request, but nothing else about the request, such as the sender. In the body it says `Request data not supplied`.

Is this a problem that can be fixed on your end or is it rather a problem in django? Or how can I go about making sure I can see which sender is harrying my endpoint?

**Comment by jsocol** [comment] 2018-06-06 18:49
I'm not sure I'm following exactly where the problem is—is there a way you could include example code?

**Comment by rschwiebert** [comment] 2018-06-06 18:56
There isn't really any code to speak of. In this case I'm just using the ratelimit middleware and viewing the email generated by the logged exception.

Maybe I will try to make a little microcosm by setting up a skeleton project with ratelimit and the AdminEmailHandler logging to see what the order of events is. I'm not sure how the exception information is handed off to the logger after the RateLimited exception is thrown.

**Comment by jsocol** [comment] 2019-02-21 21:20
Hey @rschwiebert, I was re-reading this and think I may have figured out part of where I was unclear. Are you talking about a situation where the exception is _thrown_ from some custom middleware? Or are you talking about a situation where the `RatelimitMiddleware` is installed and handles a `Ratelimited` exception?

**Comment by rschwiebert** [comment] 2019-02-22 14:32
@jsocol Hi: thanks for looking at this again.

I'll try to describe again, but I don't know how much more explicit I can be:

1. I'm using django-ratelimit
1. I have a AdminEmailHandler set to forward exceptions in emails, including the exceptions that happen when ratelimiting occurs
1. When ratelimiting happens, I get emails that look like this (redacted):

```
    Request was ratelimited: <WSGIRequest: GET '/search/results/?L=120'>
    Report Request was ratelimited: <WSGIRequest: GET '/search/results/?L=120'>`
    (pythonpath, installed apps, middleware data)
    Request data not supplied
    (settings)
```

So the one thing I wanted to see i such a traceback (the request data) isn't there.  I was hoping to note IP and or browser, for example.

It's been a long time since I looked at this. I was anticipating that the most relevant piece of data to a RateLimit event would be the request that triggered it, and that it would be available in the traceback. The very fact that "request data not supplied" appears above suggests that someone else thought so too.

So I guess I must be doing something wrong? How can I get the request data for a request that triggers a RateLimit exception to be included in said exception?

Thanks for your attention!

**Comment by jsocol** [comment] 2019-02-22 14:45
Can you tell me more about how you're using django-ratelimit?

1. Are you using the `RatelimitMiddleware`?
    1. If so, do you have a `RATELIMIT_VIEW` defined? What does it do?
2. Are you wrapping your search view in `@ratelimit()`? Can you share the args you're passing to it?
    1. If not, how are you checking the ratelimit?

The `AdminEmailHandler` is generally invoked when there are uncaught exceptions.

**Comment by rschwiebert** [comment] 2019-02-27 12:17
The answers to the above:
1.  Yes (it's on the bottom of the middleware list.)
       i. RATELIMIT_VIEW is pointed at a simple view that looks like this:

    def ratelimited_view(request, exception):
        vlogger.error('Request was ratelimited: {}'.format(request))
        return render(request, 'ringapp/ratelimited.html', {'exception': exception})

2. Yes, `@ratelimit(key='header:x-forwarded-for', rate='50/h', method='GET', block=True)`
    i. N/A

**Comment by jsocol** [comment] 2019-02-27 15:17
Ah, I'm not sure exactly what `vlogger` is, but I suspect that it's what's actually triggering the email.

When `RatelimitMiddleware` handles a `Ratelimited` exception, further exception processing does not occur by default. That's how django's middleware works, but also makes sense, because a ratelimit being imposed doesn't necessarily qualify as an exceptional condition—the server is operating properly. If someone does want to get an email every time, they should have to opt-in as you've done here (remembering that you'll get one not only when the limit is hit but on every request after that until the window expires).

Two things you can try:

1. First, to confirm this: do you still get an email at all if you comment out your `vlogger.error` call?
2. Second, try adding a kwarg `extra={'request': request}` to the `vlogger.error` call.

You're not sending any structured request data to the logger right now, you're only sending the result of `str(request)`, which, IIRC, will give you the `(pythonpath, installed apps, middleware data)` bits. It's been a little while since I dealt with this, but I think you may even find passing the whole request object into `.format` to be redundant. You could also pass `exc_info=exception`.

(One more note about the logging methods: doing the string formatting yourself makes it harder for log aggregators to identify a class of errors. You can pass string format arguments as additional positional arguments to the log message and it will only do the formatting if necessary, so structured log tools like Sentry can skip it entirely. For example `vlogger.error('Request was ratelimited: %s', request.path)`.)

**Comment by rschwiebert** [comment] 2019-02-27 16:20
@jsocol OK, i'll give these ideas all a shot. I guess the thing I was hung up on at the time was the part about "Request data not supplied" I didn't have any idea of how it was supposed to be included.  It looks like you're suggesting a few ways I couldn't divine from the docs.

For sure the email is generated by the vlogger (view logger, an instance of a typical logger you get from logging.getLogger().)

**Comment by jsocol** [comment] 2019-02-27 16:26
Yeah whenever you're using your own loggers and want Django-specific logging handlers to have request data, you can/need to pass `extra={'request': request}` to get the request context.

Since this isn't an issue in ratelimit, I'm going to close this one out and try to re-title it so other folks with similar issues can find it. Thanks for the question and patience!

**Closed by jsocol** 2019-02-27 16:26 UTC
Labels: question

**Comment by rschwiebert** [comment] 2019-02-28 11:49
Thanks for the tips. Sorry to say I'm a bit of a logging neanderthal.
