### ISSUE TITLE
ratelimit broken for Django 1.9

### ISSUE THREAD

**Issue by jvc26** [jsocol/django-ratelimit#97] opened 2015-12-13 12:18 UTC
Django removes `utils.importlib`, as this is now present in the standard library as of Python 2.7. This is a planned deprecation from Django 1.7. See related PR jsocol/django-ratelimit#96 for a suggested resolution.

**Comment by jvc26** [comment] 2016-01-09 14:41
Could a new release be put on PyPI following merge of fix PR?

**Comment by jsocol** [comment] 2016-01-09 15:45
Closing this as a duplicate of #96. Still want to follow up on the comments there and look at #98.

**Closed by jsocol** 2016-01-09 15:45 UTC
